name: Test
on:
  push:
jobs:
  test:
    name: '${{ matrix.os }}: NodeJS v${{ matrix.node }}'
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os:   [ macOS-latest, ubuntu-latest, windows-latest ]
        node: [ 8, 10, 12 ]
    steps:
      - uses: 'actions/checkout@master'
      - uses: 'actions/setup-node@v1'
        with: { node-version: "${{ matrix.node }}" }
      # - run: curl -Lo /usr/local/bin/coursier https://git.io/coursier-cli && chmod +x /usr/local/bin/coursier && /usr/local/bin/coursier --help
      # - run: npm install -g yarn
      - run: yarn install --frozen-lockfile --ignore-scripts --ignore-scripts
      - run: yarn run build
      - run: yarn lint

